services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "FABRIC"
      ICON: "https://pbs.twimg.com/media/FSpWw2eXoAAGg-C.jpg"
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      MODRINTH_PROJECTS: |
        fabric-api
        ferrite-core
        huskhomes
        lithium
        luckperms
        spark
        syncmatica
        vanilla-permissions
    volumes:
      - ./minecraft:/data
